### PR TITLE
Config encryption

### PR DESCRIPTION
**Pull request by ElectricErudite**
To enable config encryption this PR should be accepted with the other PRs for cloud and common. 

This PR introduces
1) a security section into the base cloudmesh.yaml configuration. 
valid entries are detailed in this [report.md](https://github.com/cloudmesh-community/fa19-516-144/blob/master/project/report.md) file.

2) Introduces a get_value() function. 
The get() function errors on all ordered dicts since it has a simple get call on the dict. The new function works on all dicts and is used for config encryption.
 
For more details please reference this [report.md](https://github.com/cloudmesh-community/fa19-516-144/blob/master/project/report.md).

### CODE REVIEW

**Comment by ElectricErudite** [comment]
Encryption reliant upon the approval of this PR and the approval of 
[cloud PR](https://github.com/cloudmesh/cloudmesh-cloud/pull/245)
[common](https://github.com/cloudmesh/cloudmesh-common/pull/10)

**Comment by ElectricErudite** [comment]
> did we decide that get_value was or was not implemented. I thought wehn we tried it in class we did not need a get_value as it was already there, but I am be mistaken ...

I'll test this case again and leave a comment when a python script is added to my hid repo.

**Comment by ElectricErudite** [comment]
https://github.com/cloudmesh-community/fa19-516-144/commit/377cdfc654ef4de405b19bae36e746a7e3fea240

This python script shows that every case I use get returns a None. 
The only time I receive a non using the new get_value() it is because the full path is not defined in the cloudmesh.yaml file. 

@laszewsk please let me know what you think of the script and if you can produce a counter case. If you cannot what are your thoughts on replacing get() with get_value()?

**Comment by ElectricErudite** [comment]
The build failed because it could not reference the newly merged writefd function within cloudmesh.common.util. 

@laszewsk Does the CI/CD pipeline always run with the latest instances of every Cloudmesh version?

**Comment by ElectricErudite** [comment]
The latest commit migrates (and is dependent upon) the changes made to the cloudmesh-configuration PR mentioned before.

**Comment by laszewsk** [comment]
ok i understand now what is goint on. 

a) we had a need at one poin to interrupt the yaml parsing when a field could not be found. I have not changed 2 lines in teh code to prevent this, but am not sure if it has some negative effects.

b) one should probably not us get but instad config["cloudmesh.xyz.klm"] this seems t work. WIth thsi we now have also a config.get("cloudmesh.xyz.klm", default="missing") e.g. if the value does not exist it returns missing. as said this was a two line change in config ... hope this helps

**Comment by ElectricErudite** [comment]
The build failed because it cannot access the new security classes introduces in the cms-cloud PR.

**Comment by ElectricErudite** [comment]
> get_value is not needed as we have i think the same functionality in get and [""]
You were correct. replacing the get_value function with config['some.dot.path'] worked. 

The get_value function has been removed in this [commit](https://github.com/cloudmesh/cloudmesh-configuration/pull/2/commits/27a9567d54c9aca8afef5babf197857f8b268c38). 
The build appears to fail because the cms-cloud PR has not been merged.

**Comment by laszewsk** [comment]
checks have failed so i can not merge

**Comment by ElectricErudite** [comment]
@laszewsk I'm not sure why the last test failed. it stated...
>ImportError: cannot import name 'CmsEncryptor' from 'cloudmesh.security.encrypt' (/home/travis
>/virtualenv/python3.7.1/lib/python3.7/site-packages/cloudmesh/security/encrypt.py)

The cloudmesh-cloud master branch has already merged the PR and has the CmsEncryptor in the encrypt.py file. 

Do you have any idea why this error might occur in the CI/CD pipeline despite having the correct import statement and the class being present in the file?

**Comment by ElectricErudite** [comment]
> checks have failed so i can not merge
The build error was 
> ImportError: cannot import name 'CmsEncryptor' from 'cloudmesh.security.encrypt' (/home/travis
>/virtualenv/python3.7.1/lib/python3.7/site-packages/cloudmesh/security/encrypt.py)

The cloudmesh-cloud master branch has already merged the PR and has the CmsEncryptor in the encrypt.py file.

Do you have any idea why this error might occur in the CI/CD pipeline despite having the correct import statement and the class being present in the file?

**Pull request merged**
